---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: notes-prod
spec:
  encryptedData:
    .dockerconfigjson: AgAYbPigssXltX4ORqWOTlzhcXIdEjXylCTBxO7Yhx9jcjSGS4x0R1dMl9eaZzipruFxSnoOsaSOYambbwFApuKVTAmDnIrEWKjUMcmoRfttkdHl8PGwDWqEz1kRW4xyZoZnoi49QZZs9flOomoTjB3n0QA0EA2Q8px9bAwWG5+mSKHH55BDCqlEXtdYmUhyjqcc9IvIaXdG6Cg/hQLD47epfTeVqlPmnzzPPG7xEv2fct32Fmd2dpn8mdXOmSCBBoA1R7hgirV8L0JKM546x9Tb1Qr4G4EOvJFyAalPNGqXufL3EYfaQbXvN3jgNDQ71L9XXnemKtHQm/jG5uJaPDgICF2kaAX4KEbsqqyWOT3PzafUXY0/m/cw0sp5eXUPxO3pKJr4vHQzO0gGPJpXNPtHaUuwl2dpWsCYDpgMnD/kIS2uTGvULbXyx/Q2fBmhXwZEvo7HsLpq+uhCtc/ZCTd3MnbgNyd3TNYd0GBuGxQEw0XEMaIyd/XQdUx1NtoNaVcBqYDySyxeCHdDJZwHZGv8d83GjRk8lVfVsutJhm/hGwzEEAPcw2Htgf71nbGRBWCnlmgVIXStQIPCVuAhIitBlAp4k67VZcWWDlsk/Ldaaj+BDAu/LsluFCc+Ka+k9Q/lzo5yBYgGvsgJbbJC61PFnjzID1dG5CFea8FdbXVTdGPdHtZQEaK8qw8eGxFcw+ZBfuq/20ZO8YnoyaxuBgivwyUp4mnwfbV62lRn3mP2k30GcnuaQByrzXm25j31+MWhnISBm5Yv822en1N9IpZ4TBv4tFilsPysnPconT3T3hIqhvC5E7rUYMVkPX0U+ZVPtiXhQ3Mgb6BcYnkhvxH9IlxoXxtpHmvwKD0PGc8opdpd8xabd2rZoBBg5Je7YpSIQTtmXkv2zhA1tgD1Ia51HJyqB5pu8JbntahtbHX2n0eid6DquHuGZkWM5jyLFqyRvJ1lhgP07KMq
  template:
    metadata:
      name: ghcr-secret
      namespace: notes-prod
    type: kubernetes.io/dockerconfigjson
