---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: notes-prod
spec:
  encryptedData:
    .dockerconfigjson: AgBP97hQrP/hdylXbxW6hcTnxewShFc5ZymNRy342uS3oYQRFypeK+DmB9RHKzqytePrKy1RrC1fDHalqsTIczJ/aY/i+RFogPWwSTLvxm4gUrwjoo0IXd9AyMHgfrS+mEuDoYlQ1BeLev2X9t3NsDd0MwgjpJoKN0zXr6qNA+jT9P3jUrXQ8phHCg1Du1vATyFa9/FfW+l9AZE2Xw9BY13zD3tJvHZnXg4ulumkpFTN/ABaIOM4k/atLzsfj+Dh6IA7EJPDEzbkb45CizENIJ57BOSLRW8ktN5XJqc/k83bXpD4puHgvaLbuJpa8oPgoiuPELDjOLh9WbeCwXhc8Ks7thW834gRF3tZniZxFZzCv4p0a5S3kW6usfZ2BzSIMyi2Z8jEdDt79xTMH/KhTmzfLBNkN+telGG8rldZGpt3LggF590Yj7CIjrdO6qpxZC8n0hcuoj2CaAHKH0FKCvba03UL6aabJTzPnjrrmIiCuY15wg6UEzPlZ2+MucTxyU+c2ozYG/fMskbL1++d67qhKH9vTr6/XBmvRuBbGLqlQX/iHKBkuOCpEOonMoqxbSaV8sYTxk6wVDyIVW1cO9Rg+IaJniE2z0T2SpkEiLVBfEjrniKL6MtdsRP4GXO3Wlg4F38DI3qgvx9L+JHgW8+VjRnUViL7OPvMVWNnm8p9Zbuhu31WpyQ6risoQ3EOMgFmlQREROM+dkA4u8f4AhuEU/q9ua1SZ7YTMi3xO88Pr1yTh5TSEzt/mxCjcmLQUd+zNLTpHJaf3r4/6F/o2ueC2Y9A3z2uhY6NLL7KkGMkb+fMn+17iahEMOGJy5ozSpYnQO/Ysb+Ltwwvd+JGcn2nxlmWFZV9BV0FhN7oAOr9d1fN8M+hXdW3yn8TcaQxm7weHIjrP62MWNUVBrvgiawKej4njWUY9yKLIhlvGXOU+QJQLVh6wv1Q32JhewMLuycNhzvIoikC4qVR
  template:
    metadata:
      name: ghcr-secret
      namespace: notes-prod
    type: kubernetes.io/dockerconfigjson
