replicaCount: 2

image:
  repository: ghcr.io/sarka99/notes-service
  tag: "9c566a8-dirty"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-secret

podLabels:
  environment: prod

env:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "3"
  SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: "0"

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m

autoscaling:
  enabled: false
