image:
  repository: ghcr.io/sarka99/notes-web
  tag: "812e4fd"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-secret

podLabels:
  environment: prod

resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 128Mi
    cpu: 200m

autoscaling:
  enabled: false