---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: notes-service-secrets
  namespace: notes-prod
spec:
  encryptedData:
    POSTGRES_URI: AgCBKrUFHQNEmO4dv0qyqzxGt0Rd0aD/+fevPvV1W1c59ZZLkB4Btiw6T+PmC5h2UlInLqZHvpMFbw4LO9VWKplTITxtNDbIYcbcRTGYNG4WiAi7uSElXBYwhXhCt/3+9I/D2Cocq/rDVA6or9pk96p0OFhRM2NMZiZBd4BXie2dFy1f3ctr/l+Kyk1wp9X4ALlk3T5Udz1/1+WsIVq2jBlOkX9Gn2U4DPPXnwmVCv3oOfCZbvhTcjm7fT8Fyt6A7YD0+pOA98mgioUKtu3MZtp01sCy3AakcQ6a5Gzy6B9J32kmQddGqSfBU+G+sV9lZ8lMzhsDFgdnUnDmFTeZ1qFu2jaQnFi4JPMiKCjGAamHfyI86R7aKOU1yHnE2UF1l4CMxPElqNEJsezCGKwXyu8TIWtceW3FYIW/wevcWC2QQYPsqCjPw3ClUoT5hZnxwC32Xbn8U3FLatIPh7o2TJigiWi+LEPMgVRPYPoN0FsUrU0oMXr9xKOY7sBsYBQVgz5KgR25M923vo7r1bxR/7SOay65jKAbQH455FHp1cVH8DfGmWJ9MUxPVPnUCvXhyjdhqd0OqAUxakkdaTG93TE2yRKUy8MbSTpzjz0IVehccU5Nh52q2FC4UrpJSSwB35ISCRSzFLteZJ/ZJyFYBTOH9cxpHk5WJ6cUzfkDzva4QjSVSSN62q7dh3pnMycZz821fZYNC84EG6VdFTbXyoAcSQlCqcHOKdz8ay7Kag2YxqDv8wRCCsITcivfLF0vhtD8ZQfcsT5km3expFvj3bZdoskHxSYUTqYLl9pltYQMmAUCiRaHi6rONuwQFIxHC1WPLL+PNetsSdcALYeL6gKBzRjlrF3jMRb4K+jApbnri5at
  template:
    metadata:
      name: notes-service-secrets
      namespace: notes-prod
    type: Opaque
