replicaCount: 3

image:
  repository: ghcr.io/sarka99/api-gateway
  tag: "ded297f-dirty"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-secret

podLabels:
  environment: prod

notesServiceUri: http://notes-service:80

autoscaling:
  enabled: false