replicaCount: 3

image:
  repository: europe-west3-docker.pkg.dev/project-0244e2c2-2a02-4aac-92a/prod-docker/api-gateway
  tag: 0.0.5

imagePullSecrets:
  - name: ghcr-secret

podLabels:
  environment: prod

notesServiceUri: http://notes-service:80

autoscaling:
  enabled: false